name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend deps
        run: |
          cd frontend
          npm ci

      - name: Lint frontend
        run: |
          cd frontend
          npm run lint

      - name: Test frontend
        run: |
          cd frontend
          npm test

      - name: Install backend deps
        run: |
          cd backend
          npm ci

      - name: Lint backend
        run: |
          cd backend
          npm run lint

      - name: Test backend
        run: |
          cd backend
          npm test

      - name: Build Docker images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend
          docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend

      - name: Push to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest
          docker push ghcr.io/${{ github.repository }}/backend:latest
